### ISSUE TITLE
App is crashing in Android 6.0

### ISSUE THREAD

**Issue by vivekkiran** [feathersjs/feathers-android#3]
E/AndroidRuntime: FATAL EXCEPTION: EventThread
                                                                           Process: org.feathersjs.feathersdemo, PID: 7841
                                                                           java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                               at android.os.Handler.<init>(Handler.java:200)
                                                                               at android.os.Handler.<init>(Handler.java:114)
                                                                               at android.app.Dialog.<init>(Dialog.java:119)
                                                                               at android.app.Dialog.<init>(Dialog.java:168)
                                                                               at android.support.v7.app.AppCompatDialog.<init>(AppCompatDialog.java:43)
                                                                               at android.support.v7.app.AlertDialog.<init>(AlertDialog.java:95)
                                                                               at android.support.v7.app.AlertDialog$Builder.create(AlertDialog.java:927)
                                                                               at org.feathersjs.feathersdemo.LoginActivity$1.onError(LoginActivity.java:81)
                                                                               at org.feathersjs.client.plugins.authentication.FeathersAuthentication$2.onError(FeathersAuthentication.java:174)
                                                                               at org.feathersjs.client.plugins.providers.FeathersSocketClient$6.call(FeathersSocketClient.java:178)
                                                                               at com.github.nkzawa.emitter.Emitter$OnceListener.call(Emitter.java:164)
                                                                               at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                               at com.github.nkzawa.socketio.client.Socket.onevent(Socket.java:316)
                                                                               at com.github.nkzawa.socketio.client.Socket.onpacket(Socket.java:280)
                                                                               at com.github.nkzawa.socketio.client.Socket.access$100(Socket.java:18)
                                                                               at com.github.nkzawa.socketio.client.Socket$2$2.call(Socket.java:101)
                                                                               at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                               at com.github.nkzawa.socketio.client.Manager.ondecoded(Manager.java:377)
                                                                               at com.github.nkzawa.socketio.client.Manager.access$1200(Manager.java:20)
                                                                               at com.github.nkzawa.socketio.client.Manager$3.call(Manager.java:351)
                                                                               at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                               at com.github.nkzawa.socketio.parser.Parser$Decoder.add(Parser.java:156)
                                                                               at com.github.nkzawa.socketio.client.Manager.ondata(Manager.java:369)
                                                                               at com.github.nkzawa.socketio.client.Manager.access$1000(Manager.java:20)
                                                                               at com.github.nkzawa.socketio.client.Manager$2.call(Manager.java:342)
                                                                               at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                               at com.github.nkzawa.engineio.client.Socket.onPacket(Socket.java:485)
                                                                               at com.github.nkzawa.engineio.client.Socket.access$900(Socket.java:29)
                                                                               at com.github.nkzawa.engineio.client.Socket$5.call(Socket.java:288)
                                                                               at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
                                                                               at com.github.nkzawa.engineio.client.Transport.onPacket(Transport.java:121)
                                                                               at com.github.nkzawa.engineio.client.transports.Polling.access$700(Polling.java:15)
                                                                               at com.github.nkzawa.engineio.client.transports.Polling$2.call(Polling.java:122)
                                                                               at com.github.nkzawa.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                               at com.github.nkzawa.engineio.client.transports.Polling._onData(Polling.java:132)
                                                                               at com.github.nkzawa.engineio.client.transports.Polling.onData(Polling.java:104)
                                                                               at com.github.nkzawa.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:113)
                                                                               at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by ekryski** [comment]
@vivekkiran if you have an idea and want to make a PR that would be sweet! We're pretty heavy on ReactNative right now so we aren't using native clients all that much.
